### ISSUE TITLE
An internal error occurred during: "MicroProfile properties collector".

### ISSUE THREAD

**Issue by Shrewd** [jbosstools/jbosstools-quarkus#242]
Hello

Not sure if this comes from here, but I'm getting this error when trying to edit a Quarkus application.properties file in STS.
Read some that are related but all solved, so not sure if it is back... also this one is a NoSuchMethodError.

```
java.lang.NoSuchMethodError: 'void org.eclipse.jdt.internal.core.search.JavaSearchScope.add(org.eclipse.jdt.internal.core.JavaProject, int, java.util.HashSet)'
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.createJavaSearchScope(PropertiesManager.java:422)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.createSearchScope(PropertiesManager.java:292)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.scanJavaClasses(PropertiesManager.java:215)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:145)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:113)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:104)
	at org.jboss.tools.quarkus.lsp4e.QuarkusLanguageClient.lambda$2(QuarkusLanguageClient.java:81)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

eclipse.buildId=4.22.0.202403071427
java.version=22
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es_ES
Framework arguments:  -product org.springframework.boot.ide.branding.sts4
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springframework.boot.ide.branding.sts4 -clean -data file:/C:/Users/XXXXXXXXXX

**Comment by luca-bassoricci** [comment]
I've encountered the same error after upgrade eclipse to 2024-03

**Comment by jabby** [comment]
Still present with Eclipse Java IDE 2024-06

**Comment by tomaszklucha-dev** [comment]
Any plans to resolve this issue?

**Comment by tonywestonuk** [comment]
Still present with Eclipse Java IDE 2024-09

Maybe @sbouchet knows, he was doing some work in this area a while back?

**Comment by JayGlass** [comment]
The issues so bad - I just logged in here so I could report the issue and as well, and report that I tried to disable the plugin on startup but the error still occurs - it's beyond maddening. Eclipse 2024-03.  I then relaized I had just disabled the Quarkus plugin, I went back and disabled all JBoss Tools other than the usage reporting and the issue still occurs.

**Comment by alexlitovsky** [comment]
This is a real pain. Can't open application.properties without getting this error. Still present in Eclipse 2024-09 / Quarkus Tools	1.10.100.v20231012-1606.

**Comment by brenoyure** [comment]
These errors affect, even the Jboss Tools (that i used to develop JakartaEE Projects with Wildfly).
The only way to solve was back to Eclipse 2023-12

**Comment by Sharofiddin** [comment]
I think support is stopped for this plugin :(

**Comment by damienb-opt** [comment]
At this stage, the best thing to do would be to remove the plugin from the Eclipse marketplace and reserve the tooling for commercial products since it is what "the community" is promoting anyway.

**Comment by andyhoffmanlifelens** [comment]
I am also experiencing this issue in Eclipse 2024-12.  I'm going to uninstall JBoss Tools and see if it recovers.  Error dialog shows up constantly/repeatedly when editing application.properties within a Quarkus project.

**Comment by col-panic** [comment]
Seeing this on 2025-03 in a Quarkus project.

**Comment by JayGlass** [comment]
1 year later since the original post of this problem - does anyone that maintains this project care, have any sort of ETA on a possible fix, some work arounds to resolve the issue?  It's so annoying that we often have to use a different editor to create or change the properties, then paste them into the properties file - to circumvent it erroring on every single change you make to the file O_o

**Comment by damienb-opt** [comment]
> 1 year later since the original post of this problem - does anyone that maintains this project care, have any sort of ETA on a possible fix, some work arounds to resolve the issue? It's so annoying that we often have to use a different editor to create or change the properties, then paste them into the properties file - to circumvent it erroring on every single change you make to the file O_o

Well, you can see on the commiters' activity that they are focused on the commercial closed source IDE from JetBrains. What we can hope from now on is someone to dive into Eclipse plugin development, upgrade everything, ask for a merge, wait for it to be merged and released. Personnally I've removed Quarkus tooling from Eclipse and I watch this thread :-)

**Comment by rohitlncts** [comment]
its still an issue...
eclipse.buildId=4.36.0.20250508-0813
java.version=23.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_IN
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/rroraj/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/rroraj/.eclipse_keyring -data file:/Users/rroraj/myws/

**Comment by claudioweiler** [comment]
Removed Quarkus plugin, only way.

**Comment by singyantam** [comment]
Well, that's because org.eclipse.jdt.core changed the JavaSearchScope signature from:

Hashset projectsToBeAdded) 
to:
Set<JavaProject>  projectsToBeAdded)

https://github.com/eclipse-jdt/eclipse.jdt.core/commit/4556ac22b87bd69828fed9fbcf8ce24c24fad2ec

**Comment by mcrose** [comment]
same error just minutes ago, but with full JBosstools 
`
eclipse.buildId=4.36.0.20250605-1300

java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=21.0.7+6-LTS

java.vendor=Eclipse Adoptium
java.vendor.version=Temurin-21.0.7+6

java.version=21.0.7
java.version.date=2025-04-15

java.vm.name=OpenJDK 64-Bit Server VM
java.vm.vendor=Eclipse Adoptium
java.vm.version=21.0.7+6-LTS

os.arch=amd64
os.name=Linux
os.version=6.6.97-1-MANJARO

`

**Comment by nimo23** [comment]
>I think support is stopped for this plugin :(

Can a JBOSS maintainer (e.g. @koentsje or @jeffmaury) at least confirm this, instead of receiving no response from so many people for over a year and a half? 

At the very least, it would be respectful **to archive this plugin and remove it from the Eclipse Marketplace**, instead of annoying future users of this plugin with such errors. That would be nice!

**Comment by jeffmaury** [comment]
Yes JBoss Tools has been sunset now for a while

**Comment by angelozerr** [comment]
@sbouchet has wriiten a pr content about this give up.

I dont know if it has been merged and available.

**Comment by claudioweiler** [comment]
JBoss Tools officially EOL
https://tools.jboss.org/blog/announcement-jbosstools-reaches-eol.html
